baseURL = "https://Sneferu777.github.io/operator-blog/"
locale = 'en-us'
title = 'SneferuBlog'
theme = "blowfish"

[menu]
  [[menu.main]]
    identifier = "maldev"
    name = "Malware Dev"
    url = "/categories/malware/"
    weight = 10

  [[menu.main]]
    identifier = "ad"
    name = "Active Directory"
    url = "/categories/active-directory/"
    weight = 20

  [[menu.main]]
    identifier = "websec"
    name = "Web Security"
    url = "/categories/websec/"
    weight = 30

[params.homepage]
  layout = "profile"
  showRecent = true      # This is the magic switch
  recentLimit = 5        # How many posts to show on the main page
  showRecentItems = true
