baseURL = "https://Sneferu777.github.io/operator-blog/"
locale = 'en-us'
title = 'SneferuBlog'
theme = "blowfish"


[menu]
  [[menu.main]]
    identifier = "maldev"
    name = "Malware Dev"
    url = "/categories/malware/"
    weight = 10


  [[menu.main]]
    identifier = "ad"
    name = "Active Directory"
    url = "/categories/active-directory/"
    weight = 20

  [[menu.main]]
    identifier = "websec"
    name = "Web Security"
    url = "/categories/websec/"
    weight = 30

  [[menu.main]]
   identifier = "networks"
   name = "Networks Sec"
   url = "/categories/networks/"
   weight = 40

[params.homepage]
  layout = "profile"
  showRecent = true      # This is the magic switch
  recentLimit = 5        # How many posts to show on the main page
  showRecentItems = true
  math = true


[params.author]
  name = "Sneferu"
  image = "images/sneferu.jpeg"
  headline = "Red Teamer & Malware Dev"
  bio = "Diving deep into Windows Internals and C++ exploitation."
  links = [
    { github = "https://github.com/Sneferu777" },
    { linkedin = "https://linkedin.com/in/yourprofile" }
  ]

[security]
  enableInlineShortcodes = true
  [security.http]
    methods = ['(?i)GET|POST']
    urls = ['.*']
  [security.funcs]
    getenv = ['^HUGO_', '^CI$']


[taxonomies]
  tag = "tags"
  category = "categories"
  series = "series"  # <--- Add this line
  author = "authors"

[params]
  showCodeCopyButton = true
  math = true
